[server]
port = 8080

[databases]
[databases.starknetid]
name = "starknetid"
connection_string = "xxxxxx"
[databases.sales]
name = "goerli"
connection_string = "xxxxxx"

[contracts]
starknetid = "0xXXXXXXXXXXXX"
naming = "0xXXXXXXXXXXXX"
verifier = "0xXXXXXXXXXXXX"
old_verifier = "0xXXXXXXXXXXXX"
pop_verifier = "0xXXXXXXXXXXXX"
pp_verifier = "0xXXXXXXXXXXXX"

[rpc]
url = "xxxxxx"

[starkscan]
api_url = "https://api-testnet.starkscan.co/api/v0"
api_key = "xxxxxx"

[custom_resolvers]
"0xXXXXXXXXXXXX" = ["domain.stark"]

[solana]
rpc_url = "https://xxxxxxx.solana-mainnet.quiknode.pro/xxxxxxx"
private_key = "xxxxxxx"

[altcoins]
avnu_api = "https://starknet.impulse.avnu.fi/v1"
private_key = "123"

# Ethereum (ETH) is not enabled for the moment as it is already supported by default buy.
# [altcoins.ETH]
# address = "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
# min_price = 1
# max_price = 1
# decimals = 18
# max_quote_validity = 3600 # in seconds for ETH

[altcoins.STRK]
address = "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
min_price = 500
max_price = 5000
decimals = 18
max_quote_validity = 300 # it moves faster so we reduce the quote validity

[altcoins.USDC]
address = "0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8"
min_price = 2000
max_price = 10000
decimals = 6 # not sure really
max_quote_validity = 600

[altcoins.USDT]
address = "0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8"
min_price = 2000
max_price = 10000
decimals = 18
max_quote_validity = 600
